### ISSUE TITLE
can't setup puppet module

### ISSUE THREAD

**Issue by swood** [petems/hiera-vault#12]
Hello. 

I have a very strange problem with module installation. 
I've installed vault gem, but I can't to install puppet module:

> $  puppet module install davealden/hiera_vault
> Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
> Notice: Downloading from https://forgeapi.puppet.com ...
> Error: Could not install 'davealden-hiera_vault' (latest)
>  No releases are available from https://forgeapi.puppet.com
>    Does 'davealden-hiera_vault' have at least one published release?

I think that my container hasn't internet but I'm not sure this.

**Comment by kbl** [comment]
@swood this module isn't available on puppet forge. You need to install it from "source" or tarbal.

**Comment by turbodog** [comment]
@petems could you post this up to the Forge? As noted the installation instructions don't work and if anyone searches Forge for Vault then they won't find this module.

**Comment by maxadamo** [comment]
it seems that @petems is not willing to spend any time on this repository, but I least I'd like to see tags, to avoid using master branch.

**Comment by petems** [comment]
Hi! I've been super busy recently with work but I'll see if I can both tag a release as as well as get something on the forge by end of week!

I'll also see if I can add some people to merge PR's, as well as get Travis CI working and auto-releases to Forge. I should be able to get this done by end of month. 

Remind me to fix this if I dont get these done by my set deadlines! 😅

**Comment by petems** [comment]
Currently blocked: 2FA token for my Forge account never gets sent to my email

@turbodog You able to help?

**Comment by petems** [comment]
Tag has been created for cloning from Github, will add instructions to the docs

**Comment by petems** [comment]
Released to Forge: https://forge.puppet.com/petems/hiera_vault/readme
